export const productsmock = [
  // PIZZAS
  {
    id: "1",
    tittle: "Pizza Hawaiana",
    description: "Masa, salsa full mordisco, jamón, piña en cuadritos y queso tipo mozarella.",
    price: 18500,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  {
    id: "2",
    tittle: "Pizza Tropical",
    description: "Masa, salsa full mordisco, cerezas, ciruela pasa, durazno y queso tipo mozarella.",
    price: 19200,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  {
    id: "3",
    tittle: "Pizza Bocadillo",
    description: "Masa, salsa full mordisco, bocadillo y queso tipo mozzarella.",
    price: 17800,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  {
    id: "4",
    tittle: "Pizza Carnes",
    description: "Masa, Salsa full mordisco, jamón, cabano, salami y queso tipo mozarella.",
    price: 21000,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  {
    id: "5",
    tittle: "Pizza Peperoni",
    description: "Masa, salsa full mordisco, queso tipo mozarella y pepperoni.",
    price: 19500,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  {
    id: "6",
    tittle: "Pizza Champipollo",
    description: "Masa, salsa full mordisco, champiñón, pollo y queso tipo mozarella.",
    price: 20000,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  {
    id: "7",
    tittle: "Pizza Mexicana",
    description: "Masa, salsa full mordisco, carne molida, jalapeños, tomate Cherry y queso tipo mozarella.",
    price: 20500,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  {
    id: "8",
    tittle: "Pizza Ranchera",
    description: "Masa, salsa full mordisco, maíz, huevo revuelto, carne desmechada, chorizo y queso tipo mozarella.",
    price: 21500,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  {
    id: "9",
    tittle: "Pizza Criolla",
    description: "Masa, salsa full mordisco, huevo cocido, carne desmechada con ogao, plátano maduro y queso tipo mozarella.",
    price: 22000,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  {
    id: "10",
    tittle: "Pizza Chorineta",
    description: "Masa, salsa full mordisco, tocineta, chorizo y queso tipo mozarella.",
    price: 19800,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  {
    id: "11",
    tittle: "Pizza Costipollo",
    description: "Masa, salsa full mordisco, costilla de cerdo, pollo desmenuzado en salsa BBQ y queso tipo mozarella.",
    price: 22500,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  {
    id: "12",
    tittle: "Pizza Frutos del Mar",
    description: "Masa, salsa full mordisco, salsa marinera, anillos de calamar, camarones, perejil y queso tipo mozzarella.",
    price: 23500,
    stock: 20,
    imgUrl: "",
    category: "Pizzas",
  },
  // HAMBURGUESAS
  {
    id: "13",
    tittle: "Hamburguesa Sencilla",
    description: "Pan mogolla, carne artesanal de 150gr, verduras (tomate y lechuga), cebolla crispí, queso americano y salsa full mordisco.",
    price: 12000,
    stock: 30,
    imgUrl: "",
    category: "Hamburguesas",
  },
  {
    id: "14",
    tittle: "Hamburguesa Hawayana",
    description: "Pan mogolla, carne artesanal de 150gr, verduras (tomate y lechuga), rodaja de piña caramelizada, tocineta, queso americano y salsa full mordisco.",
    price: 13500,
    stock: 30,
    imgUrl: "",
    category: "Hamburguesas",
  },
  // PERROS
  {
    id: "15",
    tittle: "Perro Pollo",
    description: "Pan perro, salchicha americana, salsa de ajo, papa rizada, pollo desmenuzado, piña triturada, trozos de tocino, huevos de codorniz y queso americano.",
    price: 11000,
    stock: 25,
    imgUrl: "",
    category: "Perros",
  },
  {
    id: "16",
    tittle: "Perro Cerdo",
    description: "Pan perro, carne cerdo (pulled pork), papa rizada, guacamole, trocitos de maduro, huevos de codorniz y queso americano.",
    price: 11500,
    stock: 25,
    imgUrl: "",
    category: "Perros",
  },
  // LASAGNA
  {
    id: "17",
    tittle: "Lasagna Full Mordisco",
    description: "Pasta de lasagna, carne a la boloñesa, jamón, pollo desmenuzado, champiñón, queso tipo mozarella + pan tostado.",
    price: 18000,
    stock: 15,
    imgUrl: "",
    category: "Lasagna",
  },
  // MAZORCADA
  {
    id: "18",
    tittle: "Mazorcada Full Mordisco",
    description: "Maíz, salchicha Zenú, huevos revueltos, pollo desmechado, carne desmechada, papa rizada, queso americano y huevos de codorniz.",
    price: 16000,
    stock: 15,
    imgUrl: "",
    category: "Mazorcada",
  },
  // AREPAS RELLENAS
  {
    id: "19",
    tittle: "Arepa Carne",
    description: "Arepa blanca, carne desmechada, ogao, queso americano y huevos de codorniz.",
    price: 9000,
    stock: 20,
    imgUrl: "",
    category: "Arepas Rellenas",
  },
  {
    id: "20",
    tittle: "Arepa Pollo",
    description: "Arepa blanca, pollo desmechado, ogao, queso americano y huevos de codorniz.",
    price: 9000,
    stock: 20,
    imgUrl: "",
    category: "Arepas Rellenas",
  },
  {
    id: "21",
    tittle: "Arepa Full Mordisco",
    description: "Arepa blanca, maíz, salchicha Zenú, huevos revueltos, papa rizada, queso americano y huevos de codorniz.",
    price: 10500,
    stock: 20,
    imgUrl: "",
    category: "Arepas Rellenas",
  },
  // SALCHIPAPA
  {
    id: "22",
    tittle: "Salchipapa Full Mordisco",
    description: "Papa francesa de 200 gr, salchicha americana, queso americano y huevos de codorniz.",
    price: 9500,
    stock: 20,
    imgUrl: "",
    category: "Salchipapa",
  },
  // ADICIONALES
  {
    id: "23",
    tittle: "Porción de papa criolla",
    description: "Porción de papa criolla, casquitos o francesa de 200gr.",
    price: 6000,
    stock: 30,
    imgUrl: "",
    category: "Adicionales",
  },
  {
    id: "24",
    tittle: "Aros de cebolla x5 uds",
    description: "Aros de cebolla.",
    price: 5000,
    stock: 30,
    imgUrl: "",
    category: "Adicionales",
  },
  {
    id: "25",
    tittle: "Tocineta",
    description: "Tocineta.",
    price: 4000,
    stock: 30,
    imgUrl: "",
    category: "Adicionales",
  },
  {
    id: "26",
    tittle: "Huevos de codorniz",
    description: "Huevos de codorniz.",
    price: 3500,
    stock: 30,
    imgUrl: "",
    category: "Adicionales",
  },
  {
    id: "27",
    tittle: "Queso americano",
    description: "Queso americano.",
    price: 3500,
    stock: 30,
    imgUrl: "",
    category: "Adicionales",
  },
];
